FROM ghcr.io/actions/actions-runner:2.314.1
# for latest release, see https://github.com/actions/runner/releases

# Based on
# https://github.com/Azure-Samples/container-apps-ci-cd-runner-tutorial/blob/main/Dockerfile.github

USER root

# install curl and jq
RUN apt-get update && apt-get install -y curl jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Make sure we have compilers etc.
RUN apt-get update && apt-get install -y build-essential