name: Self Hosted Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Activate Python
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate guidance-311
      - name: Check python
        run: python --version