name: Self Hosted Tests

# Edit to kick builds!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-self-hosted:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Check CPU Info
        run: |
          grep -E "core id|model name" /proc/cpuinfo
      - name: Check GPU Info
        run: |
          nvidia-smi
      - name: Show pip packages
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate guidance-311
          pip freeze