name: Self Hosted Tests

# Edit to kick builds!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-self-hosted:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Check System Info
        run: |
          cat /proc/cpuinfo
          echo "============================"
          cat /proc/meminfo
          echo "============================"
          lspci
      - name: Activate Python
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate guidance-311
          python --version
      - name: Try GPT-2
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate guidance-311
          python -c "from transformers import pipeline, set_seed; generator = pipeline('text-generation', model='gpt2'); set_seed(42); generator('Hello, I am a language model,', max_length=30, num_return_sequences=5)"
      - name: Show c++
        run: c++ --version
      - name: Install dependencies
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate guidance-311
          pip install -e .[test]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate guidance-311
          pytest --cov=guidance --cov-report=xml --cov-report=term-missing