name: Self Hosted Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Activate Python
        run: conda activate guidance-311
      - name: Check python
        run: python --version