name: Self Hosted Tests

# Edit to kick builds!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-self-hosted:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Show CPU Info
        run: |
          grep -E "core id|model name" /proc/cpuinfo
      - name: Show GPU Info
        run: |
          nvidia-smi
      - name: Show pip packages
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate $CONDA_ENV_311
          pip freeze
      - name: Check GPU available
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate $CONDA_ENV_311
          python -c "import torch; assert torch.cuda.is_available()"
      - name: Install dependencies
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate $CONDA_ENV_311
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .[test]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate $CONDA_ENV_311
          python -m pytest tests/ --durations=20