name: Self Hosted Tests

# Edit to kick builds!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-self-hosted:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Check CPU Info
        run: |
          cat /proc/cpuinfo | grep "core id|model name"
      - name: Check GPU Info
        run: |
          nvidia-smi